### ISSUE TITLE
Rename Proposal: wechaty-puppet-hostie -> wechaty-puppet-service

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty-puppet-service#118]
After writing the <https://wechaty.js.org/2021/01/14/wechaty-puppet-service/>, I feel the name for this module is better if rename it to `wechaty-puppet-service`.

After the rename, the environment variables will become clearer:

```sh
export WECHATY_PUPPET=wechaty-puppet-service
export WECHATY_PUPPET_SERVICE_TOKEN=puppet_service_xxx
```

Please feel free to let me know if anyone has any comments @wechaty/contributors 

To be determined.

**Comment by suntong** [comment]
Oh, thanks, finally!

I don't like the word _"hostie"_ in the very beginning --

https://github.com/wechaty/wechaty-puppet-hostie/issues/19#issuecomment-604428077

> when I was searching for the word "hostie", the first or second hit by google says it is a curse word.
> 
> > When used as a swear word, hostie may also written without the letters "h", "e" or without both letters. It is a french biblical word (the sacramental bread) often...

我一直是觉得起了个swear word这样的一个名字真有些不妥，而且它实在有太多负面相关的联系了。hostie是骂街的字， hostile，一看就带有强烈的敌意...
咱们换位思考一下，如果一个老外把他的项目起一个中文名字和“ma bi”是完全相同的字/音，那中国人听到以后皱眉头那就真算是轻的了

**Comment by huan** [comment]
@suntong Glad to know that you like the new name, cheers!

![image](https://user-images.githubusercontent.com/1361891/104819435-79e7a780-5868-11eb-9c4f-ea6ad1c7c820.png)

**Comment by huan** [comment]
The new [wechaty-puppet-service]() module has been published.

Things changed:

1. `PuppetHostie` -> `PuppetService`
1. `WECHATY_PUPPET_HOSTIE_TOKEN` -> `WECHATY_PUPPET_SERVICE_TOKEN`
2. `WECHATY_PUPPET_HOSTIE_ENDPOINT` -> `WECHATY_PUPPET_SERVICE_ENDPOINT`

**Comment by huan** [comment]
Done.
