### ISSUE TITLE
After upgrade to wechaty-puppet-service, donut bot cant`t work any more ,but with no error.

### ISSUE THREAD

**Issue by secreter** [wechaty/wechaty-puppet-service#126]
After upgrade to wechaty-puppet-service, my donut bot cant’t work any more ,but with no error.

This is the log. It seems my token is working,I don‘t konw whats wrong.

> If you get an HTTP/200 response with a JSON object body that includes your ip and port, then you are all set.
![image](https://user-images.githubusercontent.com/10734397/110203791-0ac32280-7eab-11eb-9af9-141c47af4618.png)

![image](https://user-images.githubusercontent.com/10734397/110203732-bfa90f80-7eaa-11eb-8312-45754e24563d.png)

**Comment by huan** [comment]
I'd like to suggest that you try to clone and run https://github.com/wechaty/python-wechaty-getting-started to see if it works for you.

**Comment by secreter** [comment]
It seems the same, no error but also no login event.

![image](https://user-images.githubusercontent.com/10734397/110231802-f9365500-7f54-11eb-8314-b71adf67caf6.png)

**Comment by huan** [comment]
Then it seems that your problem is related to the puppet service provider.

Please contact your puppet service provider (who provide the token to you) and ask for support.

**Comment by secreter** [comment]
This problem has been solved, thanks~

**Comment by huan** [comment]
Great to know that, you are welcome!
