### ISSUE TITLE
针对 CHATIE_ENDPOINT_LIST 支持可配置的环境变量

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty-puppet-service#141]
目前wechaty获取 token的 endpoint 只能根据指定的服务列表来获取，如果想采用自建的 chatie server，无法直接进行支持。因此需要增加相应的环境变量进行支持。

**Comment by huan** [comment]
We are using `WECHATY_SERVICE_DISCOVERY_ENDPOINT` with v0.21.3 or above, please test it and let me know if it works or not.

Thank you very much.

> Changes: we only support 1 endpoint for the new version, because there will be lots of refactoring soon.

**Comment by su-chang** [comment]
Already resolved.
