### ISSUE TITLE
使用可配置的token发现服务

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty-puppet-service#142]
目前所有的token的查找IP及端口号的请求都使用统一的token发现服务，如果有部分用户需要配置特定的token发现服务可以根据以下操作来进行：

### 自建的token发现服务
参考 [茶贴server](https://github.com/chatie/server#chatie%E8%8C%B6%E8%B4%B4) 进行搭建
例如当前token发现服务的IP和端口号为：`127.0.0.1`:`8080`

### wechaty客户端
启动客户端wechaty时，配置 SERVICE_DISCOVERY_ENDPOINT_LIST 为对应的token发现服务的IP及端口号
```
export SERVICE_DISCOVERY_ENDPOINT_LIST=127.0.0.1:8080
```

### wechaty服务端
服务端启动前，需要指定 WECHATY_APIHOST 为对应的token发现服务的IP及端口号
```
export WECHATY_APIHOST=127.0.0.1:8080
```

_注：已经存在的 token 无法支持当前配置，需要重新创建，不同类型的token支持程度不同。_

**Comment by huan** [comment]
Thank you very much for this detailed description, it's very valuable.

I hope I will be able to think about the new design this week.

**Comment by huan** [comment]
Thank you very much for this detailed description, it's very valuable.

I hope I will be able to think about the new design this week.

**Comment by huan** [comment]
Thank you very much for this detailed description, it's very valuable.

I hope I will be able to think about the new design this week.

**Comment by huan** [comment]
Close this issue because the PR has been merged.
