### ISSUE TITLE
PuppetService discoverServiceIp() endpoint<https://api.chatie.io/v0/hosties/TOKEN，it`s not work!

### ISSUE THREAD

**Issue by ZzTaidhm** [wechaty/wechaty-puppet-service#151]
robotError => token: puppet_wxwork_f677368b9c227f44 time: 2021-07-20 Tuesday 23:25:01 error: Error: PuppetService discoverServiceIp() endpoint<https://api.chatie.io/v0/hosties/puppet_wxwork_f677368b9c227f44> rejection: Error: read ECONNRESET
robotError => token: puppet_wxwork_f677368b9c227f44 time: 2021-07-20 Tuesday 23:26:00 error: Error: PuppetService discoverServiceIp() endpoint<https://api.chatie.io/v0/hosties/puppet_wxwork_f677368b9c227f44> rejection: Error: read ECONNRESET
robotError => token: puppet_wxwork_f677368b9c227f44 time: 2021-07-20 Tuesday 23:27:22 error: Error: PuppetService discoverServiceIp() endpoint<https://api.chatie.io/v0/hosties/puppet_wxwork_f677368b9c227f44> rejection: Error: read ECONNRESET
robotError => token: puppet_wxwork_f677368b9c227f44 time: 2021-07-20 Tuesday 23:31:15 error: Error: PuppetService discoverServiceIp() endpoint<https://api.chatie.io/v0/hosties/puppet_wxwork_f677368b9c227f44> rejection: Error: read ECONNRESET
robotError => token: puppet_wxwork_f677368b9c227f44 time: 2021-07-20 Tuesday 23:33:14 error: Error: PuppetService discoverServiceIp() endpoint<https://api.chatie.io/v0/hosties/puppet_wxwork_f677368b9c227f44> rejection: Error: read ECONNRESET
robotError => token: puppet_wxwork_f677368b9c227f44 time: 2021-07-20 Tuesday 23:36:23 error: Error: PuppetService discoverServiceIp() endpoint<https://api.chatie.io/v0/hosties/puppet_wxwork_f677368b9c227f44> rejection: Error: read ECONNRESET
robotError => token: puppet_wxwork_f677368b9c227f44 time: 2021-07-20 Tuesday 23:44:13 error: Error: PuppetService discoverServiceIp() endpoint<https://api.chatie.io/v0/hosties/puppet_wxwork_f677368b9c227f44> rejection: Error: read ECONNRESET
robotError => token: puppet_wxwork_f677368b9c227f44 time: 2021-07-20 Tuesday 23:47:38 error: Error: PuppetService discoverServiceIp() endpoint<https://api.chatie.io/v0/hosties/puppet_wxwork_f677368b9c227f44> rejection: Error: read ECONNRESET
robotError => token: puppet_wxwork_f677368b9c227f44 time: 2021-07-20 Tuesday 23:48:13 error: Error: PuppetService discoverServiceIp() endpoint<https://api.chatie.io/v0/hosties/puppet_wxwork_f677368b9c227f44> rejection: Error: read ECONNRESET
robotError => token: puppet_wxwork_f677368b9c227f44 time: 2021-07-20 Tuesday 23:53:50 error: Error: PuppetService discoverServiceIp() endpoint<https://api.chatie.io/v0/hosties/puppet_wxwork_f677368b9c227f44> rejection: Error: read ECONNRESET

**Comment by ZzTaidhm** [comment]
and we can get IP by API api.chatie.io/v0/hosties/your_token.
then we stop and restart(),it`s can work

**Comment by ZzTaidhm** [comment]
Error: PuppetService discoverServiceIp() endpoint<https://api.chatie.io/v0/hosties/puppet_wxwork_8cd9ddccf251b6d2> rejection: Error: read ECONNRESET
    at ClientRequest.<anonymous> (/server/release-0721/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:215:16)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by ZzTaidhm** [comment]
![WechatIMG4829](https://user-images.githubusercontent.com/20452344/126477584-0d5aed68-b8c3-445b-aa09-aadd356ccdc0.jpeg)
![WechatIMG4830](https://user-images.githubusercontent.com/20452344/126477613-635c687c-8c6e-43cb-b185-9ecf090773e6.jpeg)

**Comment by ZzTaidhm** [comment]
<img width="1077" alt="WechatIMG39" src="https://user-images.githubusercontent.com/20452344/126484968-c4b6fbc3-aa59-4473-b148-e9097a252c45.png">

**Comment by huan** [comment]
`ECONNRESET` means that your network has trouble connecting with our `api.chatie.io`.

Please make sure your network is not blocked by any routers, the best way is to run your code in a VPS outside of China.
