### ISSUE TITLE
ssl  key to small

### ISSUE THREAD

**Issue by Jesn** [wechaty/wechaty-puppet-service#161]
异常信息：

wechaty-gateway npm package update 
```
npm i wechaty-puppet-padlocal@>=0.4.1
npm i wechaty-puppet-service@0.27.6
```

![a7d55c3c2ca4afde9cd04e9111c313a](https://user-images.githubusercontent.com/5728274/129451755-5a6bc8ae-f627-4a20-9f83-fda9bf69752c.png)

Error：ssl  key to small

解决方案：
替换`wechaty-puppet-service` 里面 ca.js 文件里面的ssl证书相关信息，然后即可临时修复，我这里替换的是用2048位加密位数

![image](https://user-images.githubusercontent.com/5728274/129451897-f564a9a8-0ab3-4027-b3dc-a6a294eb7abb.png)

**Comment by huan** [comment]
Thanks for creating this issue and let me know that the 1024 bit key is not working.

I have updated the code with version 0.27.7, please try it and let me know if it works for you.

**Comment by huan** [comment]
The problem should have been solved.

Please let me know if there's any problem still exists.
