### ISSUE TITLE
EventStreamManager this.eventStream is undefined

### ISSUE THREAD

**Issue by lucifer1004** [wechaty/wechaty-puppet-service#165]
Ran into this warning message today when working on `rust-wechaty`. The rust grpc client cannot establish the event stream with the grpc server, that is to say, `wechaty-puppet-service`. I think it may be related to this warning.

**Comment by huan** [comment]
It mostly like your are running into

- https://github.com/wechaty/wechaty-puppet-service/issues/160

If so, it would be great if you can add support for TLS in the Rust Wechaty .

The work around would be downgrade the Wechaty to older version, or set environment variable to disable TLS in the Wechaty Gateway.

**Comment by lucifer1004** [comment]
I tried setting `WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT` to `true`, but TLS was still enabled when the gateway server started. 

Wechaty version: 0.68.1

> I'll definitely add TLS support later, but currently, I need to start the service to make other changes first.

**Comment by lucifer1004** [comment]
Ah, I see. In my case, I need `WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_SERVER` instead of `WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT`. The solution is [here](https://github.com/wechaty/wechaty-puppet-service/issues/160).

**Comment by lucifer1004** [comment]
> It mostly like your are running into
> 
> * [Enable TLS for all Puppet Service Clients of Wechaty Ecosystem #160](https://github.com/wechaty/wechaty-puppet-service/issues/160)
> 
> If so, it would be great if you can add support for TLS in the Rust Wechaty .
> 
> The work around would be downgrade the Wechaty to older version, or set environment variable to disable TLS in the Wechaty Gateway.

You are right. After disabling TLS, the event stream can be established now.

**Comment by huan** [comment]
Great to know that it works for you, cheers!
